repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace  # Removes extra spaces
      - id: end-of-file-fixer    # Ensures a newline at EOF
      - id: check-yaml           # Checks YAML syntax
  - repo: local
    hooks:
      - id: test-custom-script
        name: Run test script
        entry: scripts/test-script.sh
        language: system
        types: [file]
