repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace  # Removes extra spaces
        files: &files ^contents/.*\.(qmd|bib)$  # Restrict to .qmd and .bib files in contents/

      - id: end-of-file-fixer    # Ensures a newline at EOF
        files: *files
        
      - id: check-yaml           # Checks YAML syntax
        files: *files