name: Wait for Workflows

on:
  workflow_call:

jobs:
  wait-for-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install -y gh

      - name: Define Workflow Names and Check Completion
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WORKFLOW_A: "Update Changelog"
          WORKFLOW_B: "Add Contributors"
        run: |
          check_workflow_status() {
            WORKFLOW_NAME=$1
            STATUS=$(gh run list --workflow "$WORKFLOW_NAME" --json status,conclusion --jq '.[0].conclusion' 2>/dev/null)
            echo "$WORKFLOW_NAME Status: $STATUS"
            if [[ "$STATUS" != "success" ]]; then
              echo "$WORKFLOW_NAME has not completed successfully. Exiting."
              exit 1
            fi
          }

          check_workflow_status "$WORKFLOW_A"
          check_workflow_status "$WORKFLOW_B"
