name: Wait for Dependencies

on:
  workflow_call:
    inputs:
      wait-timeout:
        description: 'Timeout in seconds'
        default: '900'
        required: false
        type: string

jobs:
  wait-for-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Info Start
        run: |
          echo "Starting to wait for dependent workflows..."
          echo "Timeout setting: ${{ inputs.wait-timeout }} seconds"

      - name: Wait for "Update Changelog"
        id: wait-changelog
        uses: fkirc/wait-for-check@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: "Update Changelog"
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          repo: ${{ github.repository }}
          waitForSuccess: true
          timeoutSeconds: ${{ inputs.wait-timeout }}

      - name: Changelog Wait Status
        run: |
          echo "Changelog workflow completed with conclusion:"
          echo "${{ steps.wait-changelog.outputs.conclusion }}"

      - name: Wait for "Add Contributors"
        id: wait-contributors
        uses: fkirc/wait-for-check@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: "Add Contributors"
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          repo: ${{ github.repository }}
          waitForSuccess: true
          timeoutSeconds: ${{ inputs.wait-timeout }}

      - name: Contributors Wait Status
        run: echo "Contributors workflow completed with conclusion: ${{ steps.wait-contributors.outputs.conclusion }}"

      - name: Debug Info End
        run: echo "All dependent workflows completed successfully!"