name: Wait for Dependencies

on:
  workflow_call:
    inputs:
      wait-timeout:
        description: 'Timeout in seconds for each workflow wait'
        default: '900'
        required: false
        type: string

jobs:
  wait-for-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Info Start
        run: |
          echo "Starting to wait for dependent workflows..."
          echo "Timeout setting: ${{ inputs.wait-timeout }} seconds"
          echo "Current ref: ${{ github.event.pull_request.head.sha || github.sha }}"
          echo "Repository: ${{ github.repository }}"

      - name: Wait for "Update Changelog"
        id: wait-changelog
        uses: fkirc/wait-for-check@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: "Update Changelog"
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          repo: ${{ github.repository }}
          waitForSuccess: true
          timeoutSeconds: ${{ inputs.wait-timeout }}
          continueOnError: false

      - name: Changelog Wait Status
        run: |
          echo "Changelog workflow completed with conclusion: ${{ steps.wait-changelog.outputs.conclusion }}"
          echo "Check URL: ${{ steps.wait-changelog.outputs.checkUrl }}"

      - name: Wait for "Add Contributors"
        id: wait-contributors
        uses: fkirc/wait-for-check@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: "Add Contributors"
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          repo: ${{ github.repository }}
          waitForSuccess: true
          timeoutSeconds: ${{ inputs.wait-timeout }}
          continueOnError: false

      - name: Contributors Wait Status
        run: |
          echo "Contributors workflow completed with conclusion: ${{ steps.wait-contributors.outputs.conclusion }}"
          echo "Check URL: ${{ steps.wait-contributors.outputs.checkUrl }}"

      - name: Debug Info End
        if: success()
        run: |
          echo "All dependent workflows completed successfully!"
          echo "Total wait time completed at: $(date)"